platform :ios, '10.0'

target 'Zendesk' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftLint'

  target 'ZendeskTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
